### ISSUE TITLE
Cannot find namespace 'JSX'.

### ISSUE THREAD

**Issue by gretzke** [spectrexyz/use-nft#53] opened 2021-04-29 02:00 UTC
```
Error: node_modules/use-nft/dist/core.d.ts:6:5 - error TS2503: Cannot find namespace 'JSX'.

6 }): JSX.Element;
      ~~~
```
Somehow the `@types/react` dependency is lost when installing the package. [This](https://stackoverflow.com/a/63970016/6191842) seems to be the same issue.

It can be solved by installing `@types/react` manually in the project.

**Comment by bpierre** [comment] 2021-04-29 08:35
Ah, it must be because `JSX` is not explicitly imported. I moved to `React.FC` here: https://github.com/spectrexyz/use-nft/pull/54

Would you mind trying with this branch, and let me know if it works without adding `@types/react` to the project? Thanks :pray:

**Comment by bpierre** [comment] 2021-05-05 16:12
@gretzke I just published 0.6.1 with this change, so I am closing this issue for now. Please reopen if you can reproduce with the latest version!

**Closed by bpierre** 2021-05-05 16:12 UTC

**Comment by gretzke** [comment] 2021-05-05 22:00
Sorry I was a bit busy recently, when I tried adding the branch as a dependency in package.json the node_modules folder was empty. Unfortunately I didn't have the time to further investigate. I'll try 0.6.1 soon and if I encounter a problem I'll reopen

**Comment by bpierre** [comment] 2021-05-05 23:48
Cool no worries, thanks!

**Comment by gretzke** [comment] 2021-05-06 21:46
JSX fix works now, but I think there is a similar issue with ethers, I recently from ethers to web3js and now I get this error during compilation:

```
Error: node_modules/use-nft/dist/fetchers/ethers/types.d.ts:1:31 - error TS2307: Cannot find module '@ethersproject/contracts' or its corresponding type declarations.

1 import type { Contract } from "@ethersproject/contracts";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/use-nft/dist/fetchers/ethers/types.d.ts:2:52 - error TS2307: Cannot find module '@ethersproject/providers' or its corresponding type declarations.

2 import type { BaseProvider, JsonRpcProvider } from "@ethersproject/providers";
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

installing ethers as a dev dependency fixes the issue again
